name: Update service

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update container on the server
      uses: and-fm/cloudflared-ssh-action@v3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        private_key_filename: ${{ secrets.PRIVATE_KEY_FILENAME }}
        private_key_value: ${{ secrets.PRIVATE_KEY_VALUE }}
        port: ${{ secrets.SSH_PORT }}
        service_token_id: ${{ secrets.SERVICE_TOKEN_ID }}
        service_token_secret: ${{ secrets.SERVICE_TOKEN_SECRET }}
        commands: mkdir hello-world -v
